services:
  db:
    image: mysql:8.0
    container_name: bd_hernandez
    restart: always
   
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sillas_mesas_hernandez
    ports:
      - "3306:3306"
    volumes:
      
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: app_consultas

    depends_on:
      - db

    stdin_open: true
    tty: true
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=sillas_mesas_hernandez